# Generated by Django 5.2 on 2025-06-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_news_schedule_studentprofile_supportrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorprofile',
            name='id_docente',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('professor', 'Professor'), ('administrator', 'Administrator'), ('alumni', 'Alumni'), ('student', 'Student')], max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='target_audience',
            field=models.CharField(choices=[('professor', 'Professor'), ('administrator', 'Administrator'), ('alumni', 'Alumni'), ('student', 'Student'), ('all', 'All')], max_length=20),
        ),
    ]
