# Generated by Django 5.2 on 2025-05-04 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certificate_logos/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='certificate_signatures/')),
                ('department_name', models.CharField(default='Facultad de Ciencias Físico Matemáticas', max_length=200)),
                ('address', models.TextField(default='Av. San Claudio y 18 Sur, edif. FM1\nCiudad Universitaria, Col. San Manuel, Puebla, Pue. C.P. 72570\n01 (222) 229 55 00 Ext. 7550 y 7552')),
                ('secretary_name', models.CharField(default='Dr. Gabriel Kantún Montiel', max_length=100)),
                ('secretary_title', models.CharField(default='Secretario Académico', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoursesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_docente', models.CharField(max_length=9)),
                ('profesor', models.CharField(max_length=60)),
                ('periodo', models.CharField(max_length=6)),
                ('materia', models.CharField(max_length=80)),
                ('clave', models.CharField(max_length=50)),
                ('nrc', models.CharField(max_length=5)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hr_cont', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Courses histories',
                'ordering': ['periodo', 'materia'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=64, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='generated_certificates/')),
                ('metadata', models.JSONField(default=dict)),
                ('professor', models.ForeignKey(limit_choices_to={'user_type': 'professor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificatetemplate')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
