# Generated by Django 5.2 on 2025-06-10 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_generatedcertificate_professor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatetemplate',
            options={'ordering': ['-is_default', '-created_at']},
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_backgrounds/'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='closing_text',
            field=models.TextField(default='Se expide la presente para los fines legales que el interesado estime necesarios.', help_text='Texto de cierre'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='courses_intro',
            field=models.CharField(default='Impartió los siguientes cursos:', help_text='Texto antes de la tabla de cursos', max_length=200),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='font_family',
            field=models.CharField(choices=[('Helvetica', 'Helvetica'), ('Times-Roman', 'Times New Roman'), ('Courier', 'Courier')], default='Helvetica', max_length=50),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='include_course_table',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='include_qr_by_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='intro_text',
            field=models.TextField(default='El que suscribe, {secretary_name}, {secretary_title} de la {department_name}, de la {university_name}, por este medio hace constar que el Profesor Investigador:', help_text='Texto introductorio. Use {variables} para contenido dinámico'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='layout_type',
            field=models.CharField(choices=[('standard', 'Standard Layout'), ('formal', 'Formal Layout'), ('modern', 'Modern Layout'), ('minimal', 'Minimal Layout')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='primary_color',
            field=models.CharField(default='#000000', help_text='Color principal (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='recipient_line',
            field=models.CharField(default='A QUIEN CORRESPONDA', help_text='A quién se dirige el certificado', max_length=100),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='secondary_color',
            field=models.CharField(default='#666666', help_text='Color secundario (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='table_fields',
            field=models.JSONField(blank=True, default=list, help_text='Campos a incluir en la tabla de cursos'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='title_text',
            field=models.CharField(default='CONSTANCIA DE CARGA ACADÉMICA', help_text='Título principal del certificado', max_length=100),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='university_motto',
            field=models.CharField(default='"Pensar bien, para vivir mejor"', help_text='Lema de la universidad', max_length=100),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='university_name',
            field=models.CharField(default='Benemérita Universidad Autónoma de Puebla', max_length=200),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='verification_text',
            field=models.CharField(default='Verifique la autenticidad de este documento en:', help_text='Texto para verificación QR', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='secretary_name',
            field=models.CharField(default='Dr. José Piña', max_length=100),
        ),
        migrations.CreateModel(
            name='TemplatePreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='template_previews/')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificatetemplate')),
            ],
        ),
    ]
