# Generated by Django 5.2 on 2025-07-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_certificatetemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseshistory',
            name='listas_cruzadas',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
