# Generated by Django 5.2 on 2025-07-11 19:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_courseshistory_listas_cruzadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseshistory',
            name='bloque',
            field=models.CharField(blank=True, help_text='Bloque', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='campus',
            field=models.IntegerField(blank=True, help_text='Campus', null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='claves_programas',
            field=models.CharField(blank=True, help_text='Claves de programas', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='cred',
            field=models.IntegerField(blank=True, help_text='Créditos', null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='cupo',
            field=models.IntegerField(blank=True, help_text='Cupo máximo', null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='dias',
            field=models.CharField(blank=True, help_text='Días de clase', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='disp',
            field=models.IntegerField(blank=True, help_text='Disponibles', null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='edo',
            field=models.CharField(blank=True, help_text='Estado', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='hora',
            field=models.CharField(blank=True, help_text='Horario', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='hr_semana',
            field=models.FloatField(blank=True, help_text='Horas por semana', null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='insc',
            field=models.IntegerField(blank=True, help_text='Inscritos', null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='ligas',
            field=models.FloatField(blank=True, help_text='Ligas', null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='metodo_asistencia',
            field=models.IntegerField(blank=True, help_text='Método de asistencia', null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='modo_calif',
            field=models.CharField(blank=True, help_text='Modo de calificación', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='nivel',
            field=models.CharField(blank=True, help_text='Nivel académico', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='pp',
            field=models.CharField(blank=True, help_text='Código PP', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='salon',
            field=models.CharField(blank=True, help_text='Salón', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='secc',
            field=models.CharField(blank=True, help_text='Sección', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='source_name',
            field=models.CharField(blank=True, help_text='Nombre de la fuente', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='tipo_hr',
            field=models.CharField(blank=True, help_text='Tipo de horas', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='ua',
            field=models.CharField(blank=True, help_text='Unidad académica', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ubicación', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courseshistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='courseshistory',
            name='clave',
            field=models.CharField(help_text='Clave de la materia', max_length=50),
        ),
        migrations.AlterField(
            model_name='courseshistory',
            name='fecha_fin',
            field=models.DateField(help_text='Fecha de finalización del curso'),
        ),
        migrations.AlterField(
            model_name='courseshistory',
            name='fecha_inicio',
            field=models.DateField(help_text='Fecha de inicio del curso'),
        ),
        migrations.AlterField(
            model_name='courseshistory',
            name='hr_cont',
            field=models.IntegerField(help_text='Horas contacto del curso'),
        ),
        migrations.AlterField(
            model_name='courseshistory',
            name='id_docente',
            field=models.CharField(help_text='ID único del docente', max_length=9),
        ),
        migrations.AlterField(
            model_name='courseshistory',
            name='listas_cruzadas',
            field=models.CharField(blank=True, help_text='Código de listas cruzadas', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='courseshistory',
            name='materia',
            field=models.CharField(help_text='Nombre de la materia', max_length=80),
        ),
        migrations.AlterField(
            model_name='courseshistory',
            name='nrc',
            field=models.CharField(help_text='Número de referencia del curso', max_length=5),
        ),
        migrations.AlterField(
            model_name='courseshistory',
            name='periodo',
            field=models.CharField(help_text='Período académico (ej: 202525)', max_length=6),
        ),
        migrations.AlterField(
            model_name='courseshistory',
            name='profesor',
            field=models.CharField(help_text='Nombre completo del profesor', max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='courseshistory',
            unique_together={('id_docente', 'nrc', 'periodo')},
        ),
    ]
