# Generated by Django 5.2 on 2025-08-27 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_courseshistory_bloque_courseshistory_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='auto_sizing_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for automatic element sizing and text wrapping'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='background_pdf',
            field=models.FileField(blank=True, help_text='PDF file to use as background template', null=True, upload_to='certificate_pdf_templates/'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='layout_positions',
            field=models.JSONField(blank=True, default=dict, help_text='Positioning configuration for PDF template elements (x, y, width, height in points)'),
        ),
        migrations.AddField(
            model_name='generatedcertificate',
            name='generation_method',
            field=models.CharField(choices=[('reportlab', 'ReportLab Generated'), ('pdf_template', 'PDF Template Overlay')], default='reportlab', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='layout_type',
            field=models.CharField(choices=[('standard', 'Standard Layout'), ('formal', 'Formal Layout'), ('modern', 'Modern Layout'), ('minimal', 'Minimal Layout'), ('pdf_template', 'PDF Template with Background')], default='standard', max_length=20),
        ),
        migrations.CreateModel(
            name='TemplatePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(help_text="Name of the element (e.g., 'recipient_box', 'course_table')", max_length=50)),
                ('x', models.FloatField(help_text='X coordinate in points')),
                ('y', models.FloatField(help_text='Y coordinate in points')),
                ('width', models.FloatField(help_text='Width in points')),
                ('height', models.FloatField(help_text='Height in points')),
                ('max_width', models.FloatField(blank=True, help_text='Maximum width for tables', null=True)),
                ('max_height', models.FloatField(blank=True, help_text='Maximum height for tables', null=True)),
                ('font_size', models.IntegerField(default=11, help_text='Font size for text elements')),
                ('font_name', models.CharField(default='Helvetica', max_length=50)),
                ('alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('justify', 'Justify')], default='left', max_length=20)),
                ('text_color', models.CharField(default='#000000', help_text='Text color (hex)', max_length=7)),
                ('background_color', models.CharField(blank=True, help_text='Background color (hex)', max_length=7)),
                ('border', models.BooleanField(default=False, help_text='Show border around element')),
                ('auto_resize', models.BooleanField(default=True, help_text='Allow automatic resizing')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='certificates.certificatetemplate')),
            ],
            options={
                'unique_together': {('template', 'element_name')},
            },
        ),
    ]
