# Generated by Django 5.2 on 2025-08-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_certificatetemplate_auto_sizing_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='auto_sizing_config',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='background_pdf',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='layout_positions',
        ),
        migrations.RemoveField(
            model_name='generatedcertificate',
            name='generation_method',
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='layout_type',
            field=models.CharField(choices=[('standard', 'Standard Layout'), ('formal', 'Formal Layout'), ('modern', 'Modern Layout'), ('minimal', 'Minimal Layout'), ('background_pdf', 'Background PDF Layout')], default='standard', max_length=20),
        ),
        migrations.DeleteModel(
            name='TemplatePosition',
        ),
    ]
