# Generated by Django 5.2 on 2025-08-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_remove_certificatetemplate_auto_sizing_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='background_pdf',
            field=models.FileField(blank=True, help_text='PDF file to use as background template', null=True, upload_to='certificate_pdf_templates/'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='layout_type',
            field=models.CharField(choices=[('standard', 'Standard Layout'), ('formal', 'Formal Layout'), ('modern', 'Modern Layout'), ('minimal', 'Minimal Layout')], default='standard', max_length=20),
        ),
    ]
