# Generated by Django 5.2 on 2025-08-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_certificatetemplate_background_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='background_pdf',
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='certificate_fields',
            field=models.JSONField(blank=True, default=list, help_text='Campos a incluir en el certificado (seleccionables)'),
        ),
    ]
